package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestConformanceFixtureOwnsAccessibilityResponsiveAndReducedMotionRules(t *testing.T) {
	for _, required := range []string{"focus-visible", "min-height:44px", "@media(max-width:320px)", "@media(prefers-reduced-motion:reduce)", "animation-duration:.01ms!important", "Dialogs", "File browser", "Delete permanently?"} {
		if !strings.Contains(fixtureCSS+fixtureTemplate.Tree.Root.String(), required) {
			t.Fatalf("fixture lacks %q", required)
		}
	}
	for _, forbidden := range []string{"http://", "https://", "@import", "javascript:"} {
		if strings.Contains(fixtureCSS, forbidden) {
			t.Fatalf("fixture CSS has forbidden %q", forbidden)
		}
	}
}

func captureStdout(t *testing.T, call func()) string {
	t.Helper()
	original := os.Stdout
	reader, writer, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = writer
	defer func() { os.Stdout = original }()
	call()
	if err := writer.Close(); err != nil {
		t.Fatal(err)
	}
	data, err := io.ReadAll(reader)
	if err != nil {
		t.Fatal(err)
	}
	if err := reader.Close(); err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestThemeToolSuccessfulCommandsAndGeneratedSource(t *testing.T) {
	bundlePath, err := filepath.Abs(filepath.Join("..", "..", "internal", "theme", "testdata", "themes", "minimal"))
	if err != nil {
		t.Fatal(err)
	}
	checked := captureStdout(t, func() { check([]string{bundlePath}) })
	var checkResult map[string]any
	if err := json.Unmarshal([]byte(checked), &checkResult); err != nil || checkResult["themes"] == nil {
		t.Fatalf("check output = %q, %v", checked, err)
	}
	apiOutput := captureStdout(t, api)
	if !strings.Contains(apiOutput, `"tokens"`) || !strings.Contains(apiOutput, `"media"`) {
		t.Fatalf("API output = %q", apiOutput)
	}
	generated := captureStdout(t, func() { compileGo([]string{bundlePath}) })
	if !strings.Contains(generated, "Code generated by tools/theme") || !strings.Contains(generated, "mustRegisterBuildInput") {
		t.Fatalf("generated Go = %q", generated)
	}
	inventoryOutput := captureStdout(t, inventory)
	if !strings.Contains(inventoryOutput, "endlessfs-light") || !strings.Contains(inventoryOutput, "endlessfs-dark") {
		t.Fatalf("inventory output = %q", inventoryOutput)
	}
}

func TestThemePreviewHandlerSecurityHeadersAndAssets(t *testing.T) {
	registry, resolved, selected, err := loadPreview(nil)
	if err != nil {
		t.Fatal(err)
	}
	if selected != "endlessfs-light" || resolved.ID != selected {
		t.Fatalf("built-in preview selection = %q / %q", selected, resolved.ID)
	}
	handler := newPreviewHandler(registry, resolved)
	for path, status := range map[string]int{"/": http.StatusOK, "/fixture.css": http.StatusOK, "/assets/missing/missing": http.StatusNotFound, "/assets/" + resolved.Digest + "/theme.css": http.StatusOK} {
		request := httptest.NewRequest(http.MethodGet, path, nil)
		response := httptest.NewRecorder()
		handler.ServeHTTP(response, request)
		if response.Code != status {
			t.Fatalf("GET %s = %d", path, response.Code)
		}
		if status == http.StatusOK && response.Header().Get("Content-Type") == "" {
			t.Fatalf("GET %s lacks a content type", path)
		}
	}
	root := httptest.NewRecorder()
	handler.ServeHTTP(root, httptest.NewRequest(http.MethodGet, "/", nil))
	if !strings.Contains(root.Header().Get("Content-Security-Policy"), "script-src 'none'") || !strings.Contains(root.Body.String(), resolved.Name) {
		t.Fatalf("preview root headers/body = %v %q", root.Header(), root.Body.String())
	}
	bundlePath, err := filepath.Abs(filepath.Join("..", "..", "internal", "theme", "testdata", "themes", "minimal"))
	if err != nil {
		t.Fatal(err)
	}
	_, custom, selected, err := loadPreview([]string{bundlePath})
	if err != nil || custom.ID != selected || selected == "endlessfs-light" || selected == "endlessfs-dark" {
		t.Fatalf("custom preview selection = %q / %+v, %v", selected, custom, err)
	}
	if _, _, _, err := loadPreview([]string{filepath.Join(t.TempDir(), "missing")}); err == nil {
		t.Fatal("missing preview bundle accepted")
	}
}
