// Command theme validates bundles and serves the application-owned conformance fixture.
package main

import (
	"encoding/json"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"time"

	"github.com/applyinnovations/endlessfs/internal/theme"
)

func main() {
	if len(os.Args) < 2 {
		usage()
	}
	switch os.Args[1] {
	case "check":
		check(os.Args[2:])
	case "preview":
		preview(os.Args[2:])
	case "api":
		api()
	case "compile-go":
		compileGo(os.Args[2:])
	case "inventory":
		inventory()
	default:
		usage()
	}
}
func usage() {
	fmt.Fprintln(os.Stderr, "usage: theme check BUNDLE... | preview [BUNDLE...] | api | compile-go BUNDLE... | inventory")
	os.Exit(2)
}

func check(paths []string) {
	if len(paths) == 0 {
		usage()
	}
	registry, err := theme.LoadRegistry(paths...)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	metadata := registry.Metadata()
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(map[string]any{"themes": metadata, "themeAPI": map[string]int{"major": theme.APIMajor, "minor": theme.APIMinor}}); err != nil {
		log.Fatal(err)
	}
}
func api() {
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(map[string]any{"major": theme.APIMajor, "minor": theme.APIMinor, "tokens": theme.TokenRegistry(), "contrastPairs": theme.ContrastRegistry(), "fonts": theme.FontRegistry(), "media": theme.MediaRegistry()}); err != nil {
		log.Fatal(err)
	}
}

func compileGo(paths []string) {
	if len(paths) == 0 {
		usage()
	}
	bundles := make([]theme.Bundle, 0, len(paths))
	for _, name := range paths {
		bundle, err := theme.LoadBundle(name)
		if err != nil {
			log.Fatal(err)
		}
		bundles = append(bundles, bundle)
	}
	if _, err := theme.NewRegistry(bundles...); err != nil {
		log.Fatal(err)
	}
	fmt.Println("// Code generated by tools/theme; DO NOT EDIT.\npackage theme")
	for _, bundle := range bundles {
		manifest, err := json.Marshal(bundle.Manifest)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("func init(){mustRegisterBuildInput(%s,map[string]string{", strconv.Quote(string(manifest)))
		names := make([]string, 0, len(bundle.Files))
		for name := range bundle.Files {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Printf("%s:%s,", strconv.Quote(name), strconv.Quote(string(bundle.Files[name])))
		}
		fmt.Println("})}")
	}
}

func inventory() {
	registry, err := theme.NewRegistry()
	if err != nil {
		log.Fatal(err)
	}
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(registry.Metadata()); err != nil {
		log.Fatal(err)
	}
}

func preview(paths []string) {
	registry, err := theme.LoadRegistry(paths...)
	if err != nil {
		log.Fatal(err)
	}
	selected := "endlessfs-light"
	for _, metadata := range registry.Metadata() {
		if metadata.ID != "endlessfs-light" && metadata.ID != "endlessfs-dark" {
			selected = metadata.ID
			break
		}
	}
	resolved, _ := registry.Theme(selected)
	handler := http.NewServeMux()
	handler.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Content-Security-Policy", "default-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; style-src 'self'; img-src 'self'; font-src 'self'; script-src 'none'")
		_ = fixtureTemplate.Execute(w, map[string]string{"Theme": resolved.Name, "CSS": "/assets/" + resolved.Digest + "/theme.css"})
	})
	handler.HandleFunc("GET /fixture.css", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/css; charset=utf-8")
		_, _ = w.Write([]byte(fixtureCSS))
	})
	handler.HandleFunc("GET /assets/{digest}/{asset}", func(w http.ResponseWriter, r *http.Request) {
		asset, ok := registry.Asset(r.PathValue("digest"), r.PathValue("asset"))
		if !ok {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", asset.ContentType)
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		_, _ = w.Write(asset.Data)
	})
	server := &http.Server{Addr: "127.0.0.1:8090", Handler: handler, ReadHeaderTimeout: 5 * time.Second}
	fmt.Printf("theme preview: http://127.0.0.1:8090 (%s)\n", selected)
	log.Fatal(server.ListenAndServe())
}

var fixtureTemplate = template.Must(template.New("fixture").Parse(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EndlessFS theme conformance</title><link rel="stylesheet" href="{{.CSS}}"><link rel="stylesheet" href="/fixture.css"></head><body><header><h1>{{.Theme}}</h1><p>Theme API conformance fixture</p></header><main><section aria-labelledby="controls"><h2 id="controls">Controls and states</h2><div class="row"><button>Primary action</button><button disabled>Disabled</button><a href="#focus">Focus link</a><input aria-label="Example field" value="Field value"></div><div class="states"><span class="success">Complete</span><span class="warning">Warning</span><span class="danger">Failed</span><span class="selected">Selected</span></div></section><section><h2>File browser</h2><table><thead><tr><th>Name</th><th>Size</th><th>Status</th></tr></thead><tbody><tr><td>Example file.txt</td><td>128 KiB</td><td>Shared</td></tr><tr><td>Uploads</td><td>—</td><td>Uploading</td></tr></tbody></table></section><section><h2>Dialogs and empty states</h2><div class="panel"><h3>Empty folder</h3><p class="muted">Drop files here or choose upload.</p><button>Upload files</button></div><div class="panel danger-border"><h3>Delete permanently?</h3><p>This action cannot be undone.</p><button class="destructive">Delete</button></div></section><section><h2>Typography</h2><p class="xs">Extra small metadata</p><p>Normal body text with <code>monospace</code>.</p><p class="xl">Large heading scale</p></section></main></body></html>`))

const fixtureCSS = `*{box-sizing:border-box}body{margin:0;background:var(--efs-color-canvas);color:var(--efs-color-text-primary);font-family:var(--efs-font-interface);font-size:var(--efs-type-size-md);line-height:var(--efs-type-lineHeight-normal)}header,main{max-width:70rem;margin:auto;padding:var(--efs-spacing-pageGutter)}main{display:grid;gap:var(--efs-spacing-sectionGap)}section,.panel{background:var(--efs-color-surface);border:1px solid var(--efs-color-border);border-radius:var(--efs-radius-panel);padding:var(--efs-spacing-pageGutter)}.row,.states{display:flex;flex-wrap:wrap;gap:var(--efs-spacing-componentGap)}button,input,a{min-height:var(--efs-metric-targetMinimum);padding:var(--efs-spacing-controlPadding);border-radius:var(--efs-radius-control)}button{background:var(--efs-color-accent);color:var(--efs-color-text-inverse);border:0}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--efs-color-interaction-focusRing);outline-offset:2px}.destructive{background:var(--efs-color-danger)}.muted{color:var(--efs-color-text-muted)}.success{color:var(--efs-color-success)}.warning{color:var(--efs-color-warning)}.danger{color:var(--efs-color-danger)}.selected{background:var(--efs-color-selection-background);color:var(--efs-color-selection-text)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:var(--efs-spacing-controlPadding);border-bottom:1px solid var(--efs-color-border)}.danger-border{border-color:var(--efs-color-danger)}.xs{font-size:var(--efs-type-size-xs)}.xl{font-size:var(--efs-type-size-xl)}code{font-family:var(--efs-font-monospace)}@media(max-width:320px){header,main{padding:8px}section,.panel{padding:10px}.row{display:grid}table{font-size:12px}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}`
